:arrow_up: Bump the prettier group with 1 update (#891)
Bumps the prettier group with 1 update:
[prettier](https://github.com/prettier/prettier).

Updates `prettier` from 3.1.1 to 3.2.1
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/prettier/prettier/releases">prettier's
releases</a>.</em></p>
<blockquote>
<h2>3.2.1</h2>
<p>🔗 <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#321">Changelog</a></p>
<h2>3.2.0</h2>
<p><a
href="https://github.com/prettier/prettier/compare/3.1.1...3.2.0">diff</a></p>
<p>🔗 <a href="https://prettier.io/blog/2024/01/12/3.2.0.html">Release
note</a></p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md">prettier's
changelog</a>.</em></p>
<blockquote>
<h1>3.2.1</h1>
<p><a
href="https://github.com/prettier/prettier/compare/3.2.0...3.2.1">diff</a></p>
<h4>Fix formatting error on member chain (<a
href="https://redirect.github.com/prettier/prettier/pull/15915">#15915</a>
by <a
href="https://github.com/sosukesuzuki"><code>@​sosukesuzuki</code></a>)</h4>
<!-- raw HTML omitted -->
<pre lang="jsx"><code>// Input
test().test2().test2(thing?.something);
<p>// Prettier 3.2.0
TypeError: Cannot read properties of undefined (reading 'type')</p>
<p>// Prettier 3.2.1
test().test2().test2(thing?.something);</p>
<p></code></pre></p>
<h1>3.2.0</h1>
<p><a
href="https://github.com/prettier/prettier/compare/3.1.1...3.2.0">diff</a></p>
<p>🔗 <a href="https://prettier.io/blog/2024/01/12/3.2.0.html">Release
Notes</a></p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/prettier/prettier/commit/48ad20859bad01bf70ebc27051939c2329c52b18"><code>48ad208</code></a>
Release 3.2.1</li>
<li><a
href="https://github.com/prettier/prettier/commit/7e862bbc41a73aa5af349015bbf893a00b132482"><code>7e862bb</code></a>
Fix formatting error on member chain (<a
href="https://redirect.github.com/prettier/prettier/issues/15915">#15915</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/12f91dd1a9bbcd0a93f9f5bf91bf99f1af5f4bb9"><code>12f91dd</code></a>
Use <code>ISOString</code> for <code>getFormattedDate</code> (<a
href="https://redirect.github.com/prettier/prettier/issues/15914">#15914</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/0d9aa7b6afa1411142f3bfd930d14969af486559"><code>0d9aa7b</code></a>
Fix release notes URL in CHANGELOG.md (<a
href="https://redirect.github.com/prettier/prettier/issues/15913">#15913</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/1890d55900d8816ad838eb7d29b737268de29493"><code>1890d55</code></a>
3.2 blog post (<a
href="https://redirect.github.com/prettier/prettier/issues/15892">#15892</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/9219c130ce72dc6a73f0145c72986d5e6ead1394"><code>9219c13</code></a>
Fix clean changelog step</li>
<li><a
href="https://github.com/prettier/prettier/commit/fb08124a019bbcf9a5667256be8cb7f48ffc8772"><code>fb08124</code></a>
Remove needless call</li>
<li><a
href="https://github.com/prettier/prettier/commit/5a170bad92250126e19cf2186e06695684556c1a"><code>5a170ba</code></a>
Run <code>yarn</code></li>
<li><a
href="https://github.com/prettier/prettier/commit/c52f4418461c76708e81886d69affbc7bfccd2d0"><code>c52f441</code></a>
Clean changelog_unreleased</li>
<li><a
href="https://github.com/prettier/prettier/commit/9bb952d651b186fd7bbe3dd39521bea42f0003c5"><code>9bb952d</code></a>
Clean changelog_unreleased</li>
<li>Additional commits viewable in <a
href="https://github.com/prettier/prettier/compare/3.1.1...3.2.1">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=prettier&package-manager=npm_and_yarn&previous-version=3.1.1&new-version=3.2.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>